### ISSUE TITLE
Replace existing material definition

### ISSUE THREAD

**Issue by sdeinert** [DLR-SL/CPACS#451]
Since the current definition of a material in CPACS (cpacs/vehicles/materials/material) is based on stiffness terms, which are not readily available for materials and need to be computed from the customary material properties, we propose a new material definition for CPACS either to replace the existing one or serve as an alternative.

The proposed definition can be seen in the attached XSD file.
[material.zip](https://github.com/DLR-LY/CPACS/files/516746/material.zip)

**Comment by DLR-LY** [comment]
Firstly the introduction of the different propertyTypes seem organize the options a bit better. That looks very reasonable to me.
I also have a question concerning your proposed changes.
You made many of the entries optional and still some of the property types are 2D only. In order to avoid a large amount of property types, would it make sense to always define 3D property types and just leave the additional nodes optional? In that case we would probably need to define which directions to use for only 2D properties.

At all: Could some of the users of the material node comment on the chosen parametrization?

**Comment by sdeinert** [comment]
So the proposal was mainly derived from the MSC NASTRAN material cards MAT1,2,8,9.
The idea behind the many optional elements is that it should be possible to define for example material properties for the elastic behaviour without having to specify the allowables. As a second aspect many of these values are depending on each other, meaning that you could calculate the third value if the first two are specified (e.g. G11, G12 and poissonRatio). Since XSD does not allow such choice definitions "2 out of 3", we realized this through setting most of the elements optional counting on the user as well as the interfacing programs to check for consistency and validity of the specified data.

I would still prefer to stick with this categorized definition into isotropicProperties/anisotropic2DProperties/orthotropic2DProperties/anisotropic3DProperties as it directly tells you which types of e.g. FE elements (shells/solids, composite or metallic) could be defined using this definition simply be looking at the XML file.

Maybe we could put the common elements of all 4 types into a base type and use inheritance?

**Comment by DLR-LY** [comment]
Using inheritance at that place seems a bit artificial to me.

Would an additional element stating the category (2D/3D) be an option?

**Comment by sdeinert** [comment]
It probably would, however, then all possible elements are grouped into the one type opening up far more possibilities to define useless material definitions. The current state at least shows what should not be in there and what could be defined.

**Comment by DLR-BT** [comment]
In general, DLR_BT agrees to the proposal to replace the matarial definition with the following adaptations:
- current definition should be kept as choise in parallel for at least 1 release for smooth transition
- current postFailure definition (Option 1 for isotropic materials) should be added to new definition of isotropic material 
- (Remark: Option 2, composite damage law may be phased out for the moment, as this option is very toolspecific and may require a more general re-definition later)

**Comment by sfreund-DLR** [comment]
Thanks, I appreciate a change in this respect! The addition of strain and thermal expansion is a good feature.

As @DLR-LY mentioned, I would also prefer a solution where applicable combinations of the engineering constants are defined - explicit is better than implicit. For isotropic properties G12 is not necessary, since usually G11 and poissonRation are given - this is only one experiment instead of two for obtaining G12. For orthotropic2D, I would also perfer to state the values more explicitly. Nastran has 0 as default for G12, where I don't get the meaning of this(it would also imply G22=0). So my recommendation is to have it mandatory. G13 and G23 defaults to inf in Nastran. This is probably(please correct me, if I am mistaken) information for shell postprocessing and thus not that important for the calculation of shell displacements. These defaults should then be stated in the CPACS scheme documentaiton.

Just a side comment: The conversion of engineering constants to stiffness entities has not exactly the same definition throughout the literature. @sdeinert ,which literature do you recommend as reference - we should put this into the documentation.

The anisotropic cases are defined as stiffnesses instead of engineering constants in Nastran. Hence, the CPACS values should be called something like Kxy(Altenbach), Dxxyy(Abaqus) or Cxy(Jones) in order to explicitly distinguish them.

Maybe, we should also consider the yield strength for isotropic material. What do you think about it?

Defining anisotropic2D and orthotropic2D confused me, since also x3-terms(G13, G23) are in there. Maybe we should name it anisotropicShellPropertiesType and orthotropicShellPropertiesType? But I am not certain with this.

In Abaqus, there is the 3D-type definition a definition called "Engineering Constants" with 9 parameters, which would correspond in the proposed definition "orthotropic3D" with G11, G22, G33, Nu12, Nu13, Nu23, G12, G13, G23 as names. Do you think it is a efficient addition to the anisotropic3DPropertiesType?

Thanks for your effort creating a more productive and applicable definition! 
Best regards, Sebastian

**Comment by sdeinert** [comment]
Sorry for the very delayed response but to get this issue active again, I'll try to answer the open questions:
>For orthotropic2D, I would also perfer to state the values more explicitly. Nastran has 0 as default for G12, where I don't get the meaning of this(it would also imply G22=0). So my recommendation is to have it mandatory.

No objections to set this mandatory from my side.

>The conversion of engineering constants to stiffness entities has not exactly the same definition throughout the literature. @sdeinert ,which literature do you recommend as reference - we should put this into the documentation.

I cannot really answer this, since we do not use the current definition of CPACS for materials due to that reason. We introduced local changes in our schema to allow working with engineering constants as used in Nastran. Therefore, also this proposal to change the current CPACS implementation.

>The anisotropic cases are defined as stiffnesses instead of engineering constants in Nastran. Hence, the CPACS values should be called something like Kxy(Altenbach), Dxxyy(Abaqus) or Cxy(Jones) in order to explicitly distinguish them.

I don't know what you mean by this. E.g. Nastran QRG states these values as E1, E2, G12, etc. and not as stiffness terms.

>Maybe, we should also consider the yield strength for isotropic material. What do you think about it?

Good idea! My proposal does not claim completeness, so if anything is missing, feel free to add.

>Maybe we should name it anisotropicShellPropertiesType and orthotropicShellPropertiesType? But I am not certain with this.

I agree "Shell" and "Volume" describe the intent far better than 2D or 3D.

>In Abaqus, there is the 3D-type definition a definition called "Engineering Constants" with 9 parameters, which would correspond in the proposed definition "orthotropic3D" with G11, G22, G33, Nu12, Nu13, Nu23, G12, G13, G23 as names. Do you think it is a efficient addition to the anisotropic3DPropertiesType?

If it is useful for Abaqus, I don't see a problem adding it as a further option in the choice.

**Comment by MarAlder** [comment]
Thank you for your contributions. Since the discussion above became quite extensive, the most important points are summarized again. I have numbered these 'sub issues' so that we can work on them in a structured way and refer to them.

The complete code can be found in the [i451_material_definition](https://github.com/MarAlder/CPACS/tree/i451_material_definition) branch.
I put the code snipped on [GitHubGist](https://gist.github.com/MarAlder/12b910873ab2cb2232f4829f74604ad9) to interactively work on it.
The list with element documentations can be downloaded here: [Documentations.xlsx](https://github.com/DLR-LY/CPACS/files/2585439/Documentations.xlsx). Just modify the document and drag&drop it in the comment field.

 1. **G12 for isotropic materials**
If I have understood @sdeinert correctly, we keep the parameter G12 for the isotropic materials in order to be able to vary freely between G11, G12 and the Poisson ratio. Is this ok for @sfreund-DLR?
 2. **make G12 mendatory for orthotropic Shells** :heavy_check_mark:
This is implemented in the new schema since there were no objections. We need to see in practice whether this approach works.
3. **yield strength for isotropic material** :heavy_check_mark:
The yieldStrength element has been added. Let's see how it works in practice.
 4. **naming of the propertyTypes** 
I suggest the terms shell and solid.
 5. **stiffness terms vs. engineering constants**
For anisotropic materials (MAT2) Nastran defines Gij as element of the material matrix, while for orthotropic materials (MAT8) G12, G1Z and G2Z are shear modulus in different directions. Correct me if I'm wrong, but there is a difference in these stiffness terms as a geometric material property and engineering constants, as @sfreund-DLR points out. In order to distinguish this more clearly in CPACS we should rename the stiffness terms, right? The current difinition therefore states these values as Kij. Please make other suggestions if you like.
 6. **3D orthotropic materials**
An orthotropicSolidPropertiesType has been added. Which parameters are required? The current version begins with the following suggestion:
	
	| Element | Multiplicity | Type |
	|--|--|--|
	| G11 | [?..?] | doubleBaseType |
	| G22 | [?..?] |doubleBaseType |
	| G33 | [?..?] | doubleBaseType |
	| G12 | [?..?] | doubleBaseType |
	| G13 | [?..?] | doubleBaseType |
	| G23 | [?..?] | doubleBaseType |
	| nu12 | [?..?] | doubleBaseType |
	| nu13 | [?..?] | doubleBaseType |
	| nu23 | [?..?] | doubleBaseType |
	| referenceTemperature | [?..?] | doubleBaseType |
	| ... | ... | ...|
 7. **running the old version in parallel?**
It might make sense to replace the old materialType with the new definition. Is there a need to keep the old definition as e.g. materialOldType in CPACS?
 8. **postFailure definition for isotropic material** :heavy_check_mark:
An element postFailure has been added to the isotropicPropertiesType. It has the old postFailureType. Maybe it is worth a seperate discussion how to modify the postFailureType.
 9. **Documentation**
Let us at least find a short description for the xsd:documentation node. @sdeinert  already implemented most of these. I did some modifications, e.g. adding the SI unit. Let's complete this list:
[Documentations.xlsx](https://github.com/DLR-LY/CPACS/files/2585439/Documentations.xlsx)

**Comment by DLR-BT** [comment]
Today we had an internal discussion at DLR-BT on issue #451 with the following results, corresponding to numbers of sub-issues. We concentrated on the isotropic material behaviour and therefore do not comment specific aspects of the other property definitions. Based on the proposal an alternative .xsd schema for the material has been generated (see attachment). The documentation has not been added until now. 

In general agree with the idea to switch to a new definition of materials data closer to the kind of description in common FE solvers such as MSC-NASTRAN 

1. OK for DLR-BT. However, for isotropc materials we suggest to name the required material constants E, G and NU (as used in NASTRAN MAT1)

3. A second parameter for yield strength in compression should be added, as used in the current CPACS Schema

4. OK for DLR-BT

7. Old definition can be replaced 

8. The old definition covers aspects of isotropic and orthotropic materials. A new format is suggested for the definition of isotropic plasticity curves under different strain rates (node plasticity curves). The option 2 for composite failure can be omitted for the moment

Additional proposals: In addition we propose some new definitions for isotropic materials
•	Fatigue factor (from old definition) shifted to isotropicProperties (simplified knockdown factor)
•	Additional option to define fatigue behaviour (stress based Brown Miller approach)
•	Additional option to define damage tolerance behaviour (Walker or Forman approach)

[2018_11_28_cpacs_materialType_BT.zip](https://github.com/DLR-LY/CPACS/files/2629315/2018_11_28_cpacs_materialType_BT.zip)

**Comment by MarAlder** [comment]
Great! I only changed your new element types to _xsd:all_-elements (and in this context the materialType as well) and updated the code on [Gist](https://gist.github.com/MarAlder/12b910873ab2cb2232f4829f74604ad9).

**Comment by sdeinert** [comment]
The code on Gist looks good as far as I can see. I only noticed that for orthotropicSolidPropertiesType the multiplicity settings are missing. Also, the thermal expansion properties and the material allowables could be copied from anisotropicSolidPropertiesType as far as applicable. Is that correct?

**Comment by MarAlder** [comment]
[schematic illustration of the current schema](https://cpacs.de/svgs/materialType.svg) 
So, let's summarize:

1. **G11, G12 and nu for isotropic materials** :heavy_check_mark:
Renamed as proposed from @DLR-BT (E, G, nu); okay for @sdeinert. Unless there's no contradiction from @sfreund-DLR, we consider this aspect as done.
 2. **make G12 mendatory for orthotropic Shells** :heavy_check_mark:
This is implemented in the new schema since there were no objections. We need to see in practice whether this approach works.
3. **yield strength for isotropic material** :heavy_check_mark:
The yieldStrength element has been added. Let's see how it works in practice.
 4. **naming of the propertyTypes** :heavy_check_mark:
The terms shell and solid seem to be okay for all.
 5. **stiffness terms vs. engineering constants** :heavy_check_mark:
To distinguish between engineering constants and stiffness terms, the latter are marked Kij. This was suggested by @sfreund-DLR and was okay for @sdeinert  and @DLR-BT.
 6. **3D orthotropic materials** :hourglass_flowing_sand:
I have developed a proposal for the orthotropicSolidType as @sfreund-DLR  suggested. Please take a very close look at it, I'm not an expert in this field..
 7. **running the old version in parallel?** :heavy_check_mark:
Old definition will be replaced. @sfreund-DLR  and @DLR-BT were okay with it.
 8. **postFailure definition for isotropic material** :heavy_check_mark:
An element postFailure has been added to the isotropicPropertiesType. It has the old postFailureType. Maybe it is worth a seperate discussion how to modify the postFailureType.
 9. **Documentation** :hourglass_flowing_sand:
Please replace  the _... add description ..._ tags.
 10. **Placticity Curves** :hourglass_flowing_sand:
@DLR-BT has drawn up a proposal for the placticity curve parametrization. No objection from @sdeinert. However, I introduced plasticityCurvePoints with sub-element plasticityCurvePoint. Is that okay for @DLR-BT? This is the usual approach in CPACS and we can employ the xsd:all element in the plasticityCurveType.
 11. **Fatigue and damage tolerance** :heavy_check_mark:
Suggestions from @DLR-BT are implemented.
 12. **Thermal conductivity** :hourglass_flowing_sand:
I'll try to get a feedback from the signature community if the conductivityMap needs to be reformulated. I guess it is a directional-dependent variable?

Please take a very thorough look at the current definition ([Gist](https://gist.github.com/MarAlder/12b910873ab2cb2232f4829f74604ad9) or [cpacs_materialType.zip](https://github.com/DLR-LY/CPACS/files/2680247/cpacs_materialType.zip) and [this illustration](https://cpacs.de/svgs/materialType.svg)) As soon as we can close sub-issues 6, 9, 10 and 12 I will merge it back into the dev-branch.

**Comment by DLR-BT** [comment]
Today I had a took at the latests schema proposal and it looks fine from our point of view. Small changes are in the attached zip-file:
- no comments to sub-issues 6 / 12
- proposal with additional plasticityCurvePoints (sub-issue 10) is okay for DLR-BT
- not used complexType 'damageToleranceBehaviourType' was deleted
- documentaion (sub-issue 9) has been checked for isotropic properties only
   - few little changes (e.g. capital lettre at first wird of documentation ==> not fully consistent)
   - typos

[2018_12_17_cpacs_materialType_BT.zip](https://github.com/DLR-LY/CPACS/files/2685382/2018_12_17_cpacs_materialType_BT.zip)

**Comment by sfreund-DLR** [comment]
Hello everyone,
thanks for the many advances in this topic and sorry for the late reply! I added two minor items to the list.

1.	The renaming is a good idea. Though, I would rather suggest the usage of 3 choices with the combinations of the stiffness properties in order to avoid redundancies and misinterpretation. 
2.	????
3.	OK
4.	OK
5.	I’ve had a look at some literature. I guess Kij is more widely used in German Literature. For English literature Qij is often used for the reduced stiffness matrix (3x3) and Cij for the stiffness matrix (6x6) - both in voigt notation. 
Examples for literature:
R. M. Jones, Mechanics Of Composite Materials, 2 New edition. Philadelphia, PA: Taylor & Francis Inc, 1998.
J. N. Reddy, Mechanics of Laminated Composite Plates and Shells: Theory and Analysis, Second Edition. CRC Press, 2004.
6.	OK
7.	OK
8.	Not checked
9.	TODO - I can work on this by next week
10.	OK
11.	OK
12.	Not checked
13.	The “referenceTemperature” could be moved to “material” since it is used in every branch of the choice
14.	“thermalConductivity” is dependent on the direction, so it should be moved to each material type. (similar to thermalExpansionCoeff)

**Comment by sfreund-DLR** [comment]
sorry, I forgot a comment on 2.: I think the actual definition is sufficient

**Comment by MarAlder** [comment]
Ok, thanks for your contributions. I've [pushed ](https://github.com/MarAlder/CPACS/commit/ebc5378f04a9f6819d45bc90f6486824fea0e023) the results from last year to the [material branch](https://github.com/DLR-SL/CPACS/compare/develop...MarAlder:i451_material_definition) in order to better keep track of the proposed changes from @sfreund-DLR.

The current status can be seen here: [schema graphics](https://www.cpacs.de/svgs/materialType2.svg)

I'll now continue implementing the comments from @sfreund-DLR. Have you made any progress in sub-issue 9?

Have a nice weekend, everybody! :wave:

**Comment by MarAlder** [comment]
1. **G11, G12 and nu for isotropic materials**  :hourglass_flowing_sand:
Added three choices:
![screenshot_choices](https://user-images.githubusercontent.com/43143741/57296844-47b30800-70ce-11e9-9d39-7b4c2aab0713.png)
    * [see commit](https://github.com/DLR-SL/CPACS/commit/8e4a88892d174ec97d4d2bff61d7fa4e2396e1a5)
 2. **make G12 mendatory for orthotropic Shells** :hourglass_flowing_sand:
@sdeinert, @DLR-BT and @sfreund-DLR: anything to be further discussed before setting it back to "ok"-status?
3. **yield strength for isotropic material** :heavy_check_mark:
4. **naming of the propertyTypes** :heavy_check_mark:
5. **stiffness terms vs. engineering constants** :hourglass_flowing_sand:
changed as proposed by @sfreund-DLR  
    * [see commit](https://github.com/DLR-SL/CPACS/commit/ef3ac9b4b3be70834826f4057d10288644ee455e)
 6. **3D orthotropic materials** :heavy_check_mark:
 7. **running the old version in parallel?** :heavy_check_mark:
 8. **postFailure definition for isotropic material** :heavy_check_mark:
 9. **Documentation** :hourglass_flowing_sand:
@sfreund-DLR, @sdeinert or @DLR-BT : can you please provide a documentation oneliner for "Cij" and "Qij"?
 10. **Placticity Curves** :heavy_check_mark:
 11. **Fatigue and damage tolerance** :heavy_check_mark:
 12. **Thermal conductivity** :hourglass_flowing_sand:
feedback from the signature community: still ToDo for @MarAlder 
 13.  **moving referenceTemperature to materialType** :heavy_check_mark:
      * [see commit](https://github.com/DLR-SL/CPACS/commit/2594ed714fe249506bb6906e4f086f969354666f)
 14. **moving thermalConductivity to specific material types** :hourglass_flowing_sand:
moved thermalConductivity similar to thermalExpansionCoefficients. Ok like this?:
![screenshot_thermalConductivity](https://user-images.githubusercontent.com/43143741/57300334-e9d6ee00-70d6-11e9-80f5-9830822f3ce1.png)
     * [see commit](https://github.com/DLR-SL/CPACS/commit/2594ed714fe249506bb6906e4f086f969354666f)
    
If you don't have comments (hopefully except for sub-issue 9), please use the checkbox to indicate that I can set the status to green:
- [ ] @sfreund-DLR 
- [ ] @DLR-BT 
- [ ] @sdeinert 

Current status: [schema graphics](https://cpacs.de/svgs/materialType3.svg)

After setting sub-issues 1, 2, 5, 9, 12 and 14 to :heavy_check_mark: I will merge it back to develop.

**Comment by sdeinert** [comment]
From my side, this is ok. The only downside of adding the three choices with E, G and nu is that we now have to use a sequence for all elements. This will cause lots of annoying errors when trying to validate a CPACS file against the scheme only because the order is not correct. That was my initial thought why I avoided this sort of choice.

Regarding the documentation of Cij and Qij, I cannot offer any support as I don't know those terms either.

**Comment by DLR-BT** [comment]
From DLR-BT side the definition is okay (check focussed on isotropic material definition part).

Checking the documentation I found a small inconsistancy with respect to [N/m^2] and [Pa]. In most terms [N/m^2 ] is used, while [Pa] is used in plasticityCurvePoint definitions for tangentModulus and trueStress ==> could be changed to [N/m^2] as well, :)

**Comment by MarAlder** [comment]
I agree with @sdeinert. It would also mean that we need complex combinations of choice-elements in orthotropic material types. Thus, lets keep this little redundancy for the sake of a more easily accessible material definition. 

@sfreund-DLR : Let's find something for the remaining documentation strings on the meeting next week. 

I'll think the definition is then ready to be merged back into the development branch. DLR-OP was fine with the proposal.

**Comment by MarAlder** [comment]
I renamed the allowables. According to literature sig and eps now only have one index for the material direction, e.g., sig1t instead of sig11t. Furthermore I change the isotropicPropertiesType to sigt instead of sig11t.

See the diffs: https://github.com/MarAlder/CPACS/commit/060941ba0a3673aa9bb9e45d29a155e461a7d813

**Comment by MarAlder** [comment]
I have finished the documentation. For easy proof reading I made some screenshots from the chm-help file:

- materialType:
![screen1](https://user-images.githubusercontent.com/43143741/59512355-d62e5c80-8eb8-11e9-9439-6d09646e1831.png)
- isotropicPropertiesType:
![screen2](https://user-images.githubusercontent.com/43143741/59512449-0d047280-8eb9-11e9-844e-a46f76826be8.png)
- anisotropicSolidPropertiesType
![screen3](https://user-images.githubusercontent.com/43143741/59512565-46d57900-8eb9-11e9-8194-cdfc75e242c1.png)
- anisotropicShellPropertiesType  
![screen4](https://user-images.githubusercontent.com/43143741/59512641-6f5d7300-8eb9-11e9-9115-345b6945e9a0.png)
- orthotropicSolidPropertiesType
![screen5](https://user-images.githubusercontent.com/43143741/59512726-95831300-8eb9-11e9-8c81-795fd53b520c.png)
- orthotropicShellPropertiesType
![screen6](https://user-images.githubusercontent.com/43143741/59512758-ae8bc400-8eb9-11e9-8f6c-fbd01752ee0d.png)

Furthermore I completed the element documentation: [schema graphics](https://cpacs.de/svgs/materialType4.svg)

1. **G11, G12 and nu for isotropic materials**  :heavy_check_mark:
We finally decide not to make use of choices (would be too complicated for orthotropic material types). Instead a remark has been added to the documentation to avoid redundancy here.
 2. **make G12 mendatory for orthotropic Shells**  :heavy_check_mark:
3. **yield strength for isotropic material** :heavy_check_mark:
4. **naming of the propertyTypes** :heavy_check_mark:
5. **stiffness terms vs. engineering constants** :heavy_check_mark:
 6. **3D orthotropic materials** :heavy_check_mark:
 7. **running the old version in parallel?** :heavy_check_mark:
 8. **postFailure definition for isotropic material** :heavy_check_mark:
 9. **Documentation** :hourglass_flowing_sand:
@sdeinert, @sfreund-DLR, @DLR-BT: please give me a final feedback if everything is now described correctly.
 10. **Placticity Curves** :heavy_check_mark:
 11. **Fatigue and damage tolerance** :heavy_check_mark:
 12. **Thermal conductivity** :heavy_check_mark:
 13.  **moving referenceTemperature to materialType** :heavy_check_mark:
 14. **moving thermalConductivity to specific material types** :heavy_check_mark:

**Comment by MarAlder** [comment]
closed by #585

**Comment by sfreund-DLR** [comment]
Hi,
I'm not sure to comment on a closed issue, but there is a minor typo-like bug. The orthotropicSolidPropertiesType contains nu12 ,nu23, nu31. So looking at the compliance matrix in the documentation under "remarks", one can see nu12 and nu23 are in the lower triangle matrix, whereas nu31 is in the upper triangle matrix. I think for consistency and to reduce confusion, nu31 should be nu13. 

The initial proposal was using nu13 but it was changed during the course of this thread without notice.

What do you think?

best regards, Sebastian
