### ISSUE TITLE
Extension of Mission definition

### ISSUE THREAD

**Issue by HHOPs** [DLR-SL/CPACS#562]
It would be helpful to integrate "events" within future versions of the mission definition:

- Mass dropping (w. reference to mass properties / weight and balance) - eventually also referencing a modified aerodynamics performance map

- Air refuelling (w. reference to mass propertie / weight and balance or simplified with FF etc.)
- De-tanking strategy / sequence (w. reference to mass propertie / weight and balance etc.)

- Failure states (OEO/OEI, certain control elements inop, declare emergency within a segment etc.)

**Comment by DLR-LY** [comment]
Could you provide a schema for your proposal? 

I recommend using the Eclipse editor (Eclipse IDE for Java Developers) to simply implement your ideas into the current CPACS schema. Since I haven't finished my tutorial yet, please find a short description in the following. Don't worry about the correct implementation, I will take care of that. But in this way we have a better basis for discussion.

1. Download and install [Eclipse](https://www.eclipse.org/downloads/).

2. Use _Open File_ to load the _cpacs_schema.xsd_ file from the _schema_ folder in your CPACS directory.

3. Go to the _Design_ view. Here you have a graphical overview of the cpacs structure. Click on "cpacs : cpacsType" in the list on the right. This opens the cpacsType.
![eclipse1](https://user-images.githubusercontent.com/16148180/48908778-91cf6680-ee6b-11e8-93b8-5f5c5e1b7f6f.png)
(how wonderful _Paint_ still is...)

4. In the cpacs type open the missionsDefinitionsType:
![eclipse2](https://user-images.githubusercontent.com/16148180/48909021-639e5680-ee6c-11e8-9652-8c8ed49dd4c2.png)

5. Find the place where you want to add your elements like this:
![eclipse3](https://user-images.githubusercontent.com/16148180/48909188-e9ba9d00-ee6c-11e8-98b5-264a5372ba89.png)

6. Choose the multiplicity:
![eclipse4](https://user-images.githubusercontent.com/16148180/48909326-3dc58180-ee6d-11e8-9f32-e1ac55fdf4cb.png)

7. Finally, define your new type: Right click on the "events" element -> new Type -> "eventsType"
![eclipse5](https://user-images.githubusercontent.com/16148180/48909424-89782b00-ee6d-11e8-9377-4a6dce90c575.png)

8. Inherit this new type from "complexBaseType".

9. Right mouse click on "eventsType" -> "add Element" -> rename "NewElement" to "event"

10. Set Multiplicity of "event" to  "[1..*]" and use "Set Type" to define a new complex Type "eventType". 

11. Use "add Attribute " to add the "uID" attribute.

12. Use again "add Element" to define new elements in the event Type. Changing the type from "string" to a complex type, e.g. "airRefuellingType" allows you to add again new child elements.

13. Finally, by clicking on the three dots you may change the sequence type from "sequence" to "all" or "choice". 
![eclipse7](https://user-images.githubusercontent.com/16148180/48910300-e07eff80-ee6f-11e8-86b7-3bff09db68c3.png)

14. Design your xsd-structure, zip the file and drag&drop into the comment area to upload the file to this issue discussion.

I hope this will help to set up a schema.

**Comment by HHOPs** [comment]
Hi,

I will do that in one of the weeks to come!

Bests,

RIchard

——————————————————————————
Deutsches Zentrum für Luft- und Raumfahrt e.V. (DLR)
German Aerospace Center
Robotik und Mechatronik Zentrum | Institut für Systemdynamik und Regelungstechnik (SR) | Flugzeug-Systemdynamik (FLS)
Robotics and Mechtronics Center | Institute of System Dynamics and Control | Aircraft Systems Dynamics
Münchener Straße 20, D-82234 Weßling, Deutschland/Germany | Geb. 135, Raum 1209 | 48.083081, 11.275519<https://goo.gl/maps/g1PfK3KQfT72>
Dipl.-Ing. (Univ.) Richard Kuchar | Wissenschaftlicher Mitarbeiter
Telefon +49 (0) 8153 28-2497 | Telefax +49 (0) 8153 28-1441 | richard.kuchar@dlr.de<mailto:richard.kuchar@dlr.de>
www.dlr.de/sr<http://www.dlr.de/sr/>
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: DLR-LY [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. November 2018 16:05
An: DLR-LY/CPACS
Cc: Kuchar, Richard; Author
Betreff: Re: [DLR-LY/CPACS] Extension of Mission definition (#562)


Could you provide a schema for your proposal?

I recommend using the Eclipse editor (Eclipse IDE for Java Developers) to simply implement your ideas into the current CPACS schema. Since I haven't finished my tutorial yet, please find a short description in the following. Don't worry about the correct implementation, I will take care of that. But in this way we have a better basis for discussion.

1.      Download and install Eclipse<https://www.eclipse.org/downloads/>.

2.      Use Open File to load the cpacs_schema.xsd file from the schema folder in your CPACS directory.

3.      Go to the Design view. Here you have a graphical overview of the cpacs structure. Click on "cpacs : cpacsType" in the list on the right. This opens the cpacsType.
[eclipse1]<https://user-images.githubusercontent.com/16148180/48908778-91cf6680-ee6b-11e8-93b8-5f5c5e1b7f6f.png>
(how wonderful Paint still is...)

4.      In the cpacs type open the missionsDefinitionsType:
[eclipse2]<https://user-images.githubusercontent.com/16148180/48909021-639e5680-ee6c-11e8-9652-8c8ed49dd4c2.png>

5.      Find the place where you want to add your elements like this:
[eclipse3]<https://user-images.githubusercontent.com/16148180/48909188-e9ba9d00-ee6c-11e8-98b5-264a5372ba89.png>

6.      Choose the multiplicity:
[eclipse4]<https://user-images.githubusercontent.com/16148180/48909326-3dc58180-ee6d-11e8-9f32-e1ac55fdf4cb.png>

7.      Finally, define your new type: Right click on the "events" element -> new Type -> "eventsType"
[eclipse5]<https://user-images.githubusercontent.com/16148180/48909424-89782b00-ee6d-11e8-9377-4a6dce90c575.png>

8.      Inherit this new type from "complexBaseType".

9.      Right mouse click on "eventsType" -> "add Element" -> rename "NewElement" to "event"

10.  Set Multiplicity of "event" to "[1..*]" and use "Set Type" to define a new complex Type "eventType".

11.  Use "add Attribute " to add the "uID" attribute.

12.  Use again "add Element" to define new elements in the event Type. Changing the type from "string" to a complex type, e.g. "airRefuellingType" allows you to add again new child elements.

13.  Finally, by clicking on the three dots you may change the sequence type from "sequence" to "all" or "choice".
[eclipse7]<https://user-images.githubusercontent.com/16148180/48910300-e07eff80-ee6f-11e8-86b7-3bff09db68c3.png>

14.  Design your xsd-structure, zip the file and drag&drop into the comment area to upload the file to this issue discussion.

I hope this will help to set up a schema.

**Comment by MarAlder** [comment]
closed by #716.
