### ISSUE TITLE
Documentation clarification for symmetry

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-SL/CPACS#580]
The documentation is somewhat unclear. Elements using the `stringUIDBaseType` to refer to another component have the optional attribute `symmetry` with 3 options.
The documentation says that using an value of e.g. `symm` "refers to the geometric component that has a symmetry attribute and refers only to the symmetric side of the geometric component".

That's misleading, as our current element that has e.g. a `<parentUid symmetry="symm">` is the one with the `symmetry` attribute, not the other one being referred to, or am I mistaken?

**Comment by MarAlder** [comment]
It is indeed not the best naming for the attribute. Do you think a better documentation will be sufficient or do we need a renaming? 

Since attribute names do not need to be unique the current version is valid. To avoid confusion one could rename the attribute to `symmetryReference` or something like this to distinguish it from `symmetry`. But older data-sets would suddenly be invalid.

**Comment by MarAlder** [comment]
Documentation updated with CPACS 3.4 (see [here](https://www.cpacs.de/documentation/CPACS_3_4_0_Docs/html/89b6a288-0944-bd56-a1ef-8d3c8e48ad95.htm)). Renaming remains subject to a revision of the whole symmetry strategy.
