### ISSUE TITLE
uIDs should not be required

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#608]
Based on #607 I suggest that uIDs should not be required. 

I know that it has been changed in CPACS 3, but I don't get the meaning. Why not only set uIDs when needed?

**Comment by sdeinert** [comment]
Actually the request to make uIDs required was also made from my side.

The main problem, which is now also introduced with the CPACS creator features of the TiGL viewer, is if you want to add a new component (e.g. a wing) to your existing CPACS which needs to reference any existing component (e.g. fuselage as parentUID) with an application.
If fuselage has no uID specified you would be required to first set a uID of the existing component before you can reference it and then create the wing. In the program this would have to be triggered from the "addWing" method, which makes it quite ugly to handle if there are many uIDs missing.
Therefore, the proposal was that any component that can be referenced should already be prepared so that it can be referenced, thus, making uIDs required.

**Comment by MarAlder** [comment]
Since many tools access the uIDs directly, we leave it that way. **I will just set the uID of the transformation type to optional again.** 

We should think about making the tools independent from the uIDs in the future and accessing the information in CPACS via xpath, xlink etc.

**Comment by MarAlder** [comment]
### Important commit: 86fc4c2

The `uID` elements are **set to optional** in the following types:
- `transformationType`
- `pointType`
- `pointXType`
- `pointYType`
- `pointZType`
- `pointXYType`
- `pointXZType`
- `pointYZType`
- `pointXYZType`
- `pointAbsRelType`

It is **still required** for `positioningsType` because I'm not sure which software might use this attribute directly.
