### ISSUE TITLE
toolspecific node "tool" should have a required attribute such as "name" or similar

### ISSUE THREAD

**Issue by anpari** [DLR-SL/CPACS#654]
This is to avoid read and write ambiguities. Especially writing to the file can result in some unwanted behaviour. 

Suppose we have two tools "Tool A" and "Tool B". If both tools execute and write model-independent information to the file, such as "toolRuntime" usign an XPATH such as:

```
"/cpacs/toolspecific/tool/ToolA/runTime"
```

the resulting file may end up looking like this:

```
<cpacs>
  <toolspecific>
    <tool>
        <ToolA>
           <runTime>
        <ToolB>      
           <runTime>
...   

```
instead of like this:

```
<cpacs>
  <toolspecific>
    <tool>
        <ToolA>
           <runTime>
    <tool>
        <ToolB>      
           <runTime>
...   
```
in the latter case, the actual tool node "ToolA"/"ToolB" would not be required if we simply used an attribute to specify the "tool" node.

**Comment by ArneBachmannDLR** [comment]
I thought the old convention was to specify the tool identifier directly under toolspecific:
```
<cpacs>
  <toolspecific>
    <toolA>
...
```
But the schema says otherwise now. Not sure about the upcoming approach using namespaces though...
Anyway in your case it should rather be
```
<cpacs>
  <toolspecific>
    <tool>
      <name>a</name>
      <runTime>
    </tool>
...
```
and maybe a predicate may help and avoid the need for an attribute:
```
/cpacs/toolspecific/tool[name/text()="a"]
```

**Comment by andreas-pr-dlr** [comment]
I'd argue that it's much more convenient to use attributes to determine the exact branch reserved of your tool (and tool mode), instead of looking for a value "name" somewhere in the descendants of all "toolspecific" sub-trees.

**Comment by ArneBachmannDLR** [comment]
Yes, but I gave you an option that should work now, rather after a lengthy discussion with schema-breaking changes :-) And it would be equivalent to a attribute selector, if you restrict the tool name to a token type (e.g. allowing no spaces).

**Comment by andreas-pr-dlr** [comment]
I'm making a suggestion for change in the next iteration of CPACS.
Sure we can use the predicate pattern instead of attributes as in much of the rest of CPACS. In practice, however, people are not proficient using predicates, which is reflected in the code I have to touch on a daily basis.

**Comment by MarAlder** [comment]
Maybe some background why the actual tool data is now contained in an additional `tool` element in the new definition.

In order to implement nodes from another schema, we need the `xsd:any` element. In the old defnition the `toolspecific` type contained a list with tool names. Since this list of tools is not known a priori according to new CPACS schema, we need a [1..inf] sequence of elements which serve as a container for information we want the user to specify (name and version) together with the any-element. It is not possible to specify a [1..inf] sequence of any-elements directly in XSD. 

![grafik](https://user-images.githubusercontent.com/43143741/93484509-46b8fa00-f902-11ea-8ed7-6444ed722603.png)

As you can see in the [detailed report](https://github.com/DLR-SL/CPACS/files/3667369/report_TS.pdf) from #484 we initially specified `toolName` and `toolVersion` as an attribute. The feedback from the community (mainly DLR-SL) was that specifying `name` and `version` as child element of `tool` is more intuitive and more consistent to the general CPACS implementation. 

Personally, I have no deep feelings for the first or second solution as long as the information can be clearly stored in CPACS. In general, one approach is to define the actual data of a node as sub-elements while specifying additional metadata as attribute (see for example [here](https://www.w3schools.com/xml/xml_dtd_el_vs_attr.asp)). The distinction between data and metadata is not always easy, though. 

Since the current approach is already released I suggest to wait for the first user feedback from the current projects and put the attribute-approach to discussion if it turns out the be the better approach. We should also provide a tutorial of how to implement a toolspecific namespace and how to correctly query the data using XPATH.

**Comment by jbussemaker** [comment]
I agree with @andreas-pr-dlr that practically speaking tool developers are not proficient using predicates. When testing their tool they are probably only testing using one `<tool>` element in the `<toolspecific>` section, leading to xpaths that treat the CPACS file as always having only one `<tool>` element.

The point you mention @MarAlder about attributes vs sub-elements is a good one. I think that attributes are better for metadata and sub-elements are better for data. This then means that the name and version of the tool is better specified as attributes, since to me this seems more like metadata than data. Additionally it would force tool developers to think about dealing with the tool name attribute when reading from and writing to toolspecific data and prevent problems with multiple tool elements being present in the CPACS file at once.

My proposal (if you really need to keep the "tool" node name!):
```xml
<cpacs>
  <toolspecific>
    <tool name="toolA" version="0.9" xmlns="http://tool.namespace/">
      ...
    </tool>
    <tool name="toolB" version="1.5" xmlns="http://othertool.namespace/">
      ...
    </tool>
  </toolspecific>
</cpacs>
```

I'm not sure how this would affect XSD validation, however.

**Comment by MarAlder** [comment]
@jbussemaker and @andreas-pr-dlr, I completely understand your concerns and I like above approach, which was exactly one of the options proposed [in my report](https://github.com/DLR-SL/CPACS/files/3667369/report_TS.pdf). Feedback from tool developers favored the current solution, though. Since the current approach is already released in [CPACS 3.2](https://github.com/DLR-SL/CPACS/projects/4), we have two options now:
1. **Change the implementation again in CPACS 3.3/3.x**. In projects such as Diabolo, Exact, Agile or the standard workflow people have been told to adopt their tools to CPACS 3.2. Thus, we need a communication strategy for these projects to explain that their work will require changes in the next release again.
2. **Continue testing the current solution in practice** and cross fingers that tool developers are using XPath correctly.

Maybe we should ask the tool developers?

Anyway, there was already a request for more detailed tutorials on the implementation of toolspecific schemes using XPath and TiXI (with all the required namespace registration and so on). Maybe someone has a student currently working on a specific tool who could write such a documentation for https://github.com/DLR-SL/CPACS_Seminar?

**Comment by jbussemaker** [comment]
I think we should aim for something better than crossing our fingers :)

**Comment by MarAlder** [comment]
Have faith, @jbussemaker, have faith 😄 

I promise to bring the above options as a discussion options in the next CPACS user/developer meeting before the next official release. The community should decide.

**Comment by jnwalther** [comment]
Maybe a good intermediate step would be to come up with a strategy to raise awareness and educate people. Honestly, I am quite confident people will be able to use predicates once you show them how it works. Maybe @MarAlder and @andreas-pr-dlr could put together a couple of slides which outline the issue and show the solution proposed by @ArneBachmann. These could be distributed in ongoing projects to avoid the need to change CPACS versions.

**Comment by CLiersch** [comment]
From my point of view, the attribute approach and the sub-node approach are quite similar. Maybe attributes would be a bit more classical XML style, while a <name> subnode is more CPACS like. However, from a user's perspective I do not see much difference in addressing either '/cpacs/toolspecific/tool[@version="3.1.1"]/', or '/cpacs/toolspecific/tool[version="3.1.1"]/'. 

In fact, my XPATH-statements currently look like this (not very beautiful, but working):
/cpacs/toolspecific/tool[version="3.1.1"]/*[name()="liftingLine"][@schemaVersion="3.2.0"]/ts:aircraftModelUID
(Maybe there are a more elegant ways to safely address the right tool node, but I have not found them yet .)

I can just imagine, that addressing the name and version itself could be easier if they would be attributes, because now for me it looks like this:
'/cpacs/toolspecific/tool[version="3.1.1"]/*[name()="liftingLine"][@schemaVersion="3.2.0"]/../name'

So, I could imagine that your proposed attribute-approach could also be a good solution and CPACS decisions have never been carved in stone, but changing an existing solution should bring a significant benefit to the users. So, what would be the benefit of this change?

**Comment by MarAlder** [comment]
The current solution seems to be established in the CPACS community. Implementations of the current scheme, for example in MDAx, have been successful. Educational examples are currently being compiled in a joint activity of TiGL/TiXI, RCE and CPACS developers, taking into account the proposed explanations.
