### ISSUE TITLE
performanceRequirements: occurence and choice between missionUID and pointPerformanceUID?

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#706]
Does the ability to define multiple [`performanceCases`](https://www.cpacs.de/documentation/CPACS_development/html/0bc2344f-bb6e-0cfa-7fff-e75a607a5a85.htm) as well as multiple [`pointPerformanceUIDs`](https://www.cpacs.de/documentation/CPACS_development/html/3e4d0e68-17b8-3016-a36a-97a86b2cd340.htm) open up an ambiguous approach to data definition because referring to a new `pointPerformanceUIDs` should open a new `performanceCase`? 

Furthermore, should there be a choice between `pointPerformanceUID` and `missionUID` or are there reasons to refer to both at the same time?

![grafik](https://user-images.githubusercontent.com/43143741/111991024-23227680-8b14-11eb-9bfb-85b425bcd819.png)

maybe interesting for: @HHOPs, @ErwinMoerland, @sdeinert

**Comment by ErwinMoerland** [comment]
> Does the ability to define multiple [`performanceCases`](https://www.cpacs.de/documentation/CPACS_development/html/0bc2344f-bb6e-0cfa-7fff-e75a607a5a85.htm) as well as multiple [`pointPerformanceUIDs`](https://www.cpacs.de/documentation/CPACS_development/html/3e4d0e68-17b8-3016-a36a-97a86b2cd340.htm) open up an ambiguous approach to data definition because referring to a new `pointPerformanceUIDs` should open a new `performanceCase`?

> Furthermore, should there be a choice between `pointPerformanceUID` and `missionUID` or are there reasons to refer to both at the same time?

Maybe this might answer both questions at the same time:

For the pointPerformances to be considered, a specific state of the aircraft is needed. Within the `<pointPerformanceDefinition>`, there is a choice element to define at which part of the mission the point performance should be considered:

![grafik](https://user-images.githubusercontent.com/40854909/113299769-82933a00-92fd-11eb-8889-7321cd904718.png)

`<segmentUID>` --> at the end of indicated segment of the mission as defined in performanceCase
`<massFraction>` --> at the defined  massFraction within the mission as defined in performanceCase (mCurrent/mTO)
`<fuelFraction>` -->  at the defined fuelFraction within the mission as defined in performanceCase (mFuelCurrent/mFuelTO)

so, for each pointPerformance to be considered, a reference to a mission is needed to be able to determine the state of the aircraft (mainly its actual weight). Since regularly _multiple_ pointPerformances are considered for the _same part of a specific mission_, multiple `pointPerformanceUIDs `are allowed in conjunction with a single `missionUID`.

What could be done for a more clear definition:

create a choice between `pointPerformanceUIDs` and `missionUID` within the `performanceRequirements` indeed and in exchange for this add a reference to the `missionUID ` next to the aforementioned three choices (segmentUID, massFraction, fuelFraction) within the pointPerformanceDefinition itself. This seems a more clean approach, since this link should be vehicle-independent.

what do you think?

**Comment by MarAlder** [comment]
Ok, thanks for your explanations!, so you propose the following solution if I understand correctly:
![grafik](https://user-images.githubusercontent.com/43143741/114021141-a829c180-9870-11eb-881c-49f65c00a55a.png)

As the `missionUID` can be derived from the `segmentUID` (and thus to provide inconsistency at this point) we could also implement a solution like this:
![grafik](https://user-images.githubusercontent.com/43143741/114022130-baf0c600-9871-11eb-9a37-aea7120a109b.png)

From a non-expert's point of view, I could also imagine that the coupling between point-performances and a mission is feasable to be treated vehicle-dependet (*for a given vehicle it is required to fulfill a number of vehicle-independent pointPerformance definitions with respect to a vehicle-independent mission definition*). Then the only change would be to make the `missionUID` obligatory in `pointPerformanceCase`. 

Please let me know your preferred solution and have a final look at the occurences before we close this issue.
