### ISSUE TITLE
Finalization performanceRequirements & missionDefinitions

### ISSUE THREAD

**Issue by ErwinMoerland** [DLR-SL/CPACS#716]
I have finalized creating the extensive performanceCases node for 5 missions of the Diabolo project.

Some issues arose, in my opinion small enough to be considered finetuning the CPACS v3.3-RC towards the official release.

### Concerning flightPerformanceRequirements

- [x] the differences in node-naming for the performanceRequirements seems confusing.
current: `/cpacs/.../performanceRequirements/flightPerformanceReqs/flightPerformanceReq`
suggest to rename to: `/cpacs/.../performanceRequirements/flightPerformanceRequirements/flightPerformanceRequirement`
- [x] `/cpacs/.../performanceMaps/.../specificPerformanceMap` does not need attribute `uID` (both the engine and aerodynamic performanceMaps)

### Concerning missionDefinitions

- [x] When adding child `missionDefinitions`, can the order of the obligatory children be pre-set to `missions`, `segmentBlocks`, `segments` (currently inserts: `segments`, `missions`, `segmentBlocks`)
- [x] `/cpacs/../missionDefinitions/missions/mission/startCondition/positionXYZ` is added without children. Force `../X`, `../Y`, `../Z` to be defined?

### Concerning segmentBlocks

For XPATH: `/cpacs/../missionDefinitions/segmentBlocks/segmentBlock/variableSegments/variableSegment`:
- [x] no `uID` attribute needed (no need to link to this node)
- [x] how to link to endConditions that have children, e.g. use: `range` or `range/x` or `x`?

### Concerning segments

- [x] `/cpacs/.../missionDefinitions/segments/segment/segmentType` `xsd:restriction` needs following additions:
```xml
<xsd:enumeration value="warmUp"/>
<xsd:enumeration value="loiter"/>
<xsd:enumeration value="massFraction"/>
<xsd:enumeration value="mass"/>
```
(loiter is considered different than holding, which is representing a 1min-1min-1min-1min sequence) 

- [x] segmentType "storeRelease" needs an endCondition stating which stores are released. Proposed structure:
```xml
<endCondition>
    <releasedStores>
    	<releasedStore>
    		<uID>storeUID_1</uID>
    		<quantity>1</quantity>
    	</releasedStore>
    	<releasedStore>
    		<uID>storeUID_2</uID>
    		<quantity>3</quantity>
    	</releasedStore>
    </releasedStores>
   </endCondition>
```

- [x] Credit distance Y/N cannot be set yet. Suggest to add optional node to `/cpacs/.../missionDefinitions/segments/segment`:
```xml
<creditDistance>
```
type: boolean
occurrence: 0..1
documentation: _indicates whether the distance flown during the segment is to be taken into account in the segmentBlock's distance calculation_

- [x] 	In `/cpacs/../segment/constraints/constraint`, the node `<continuity>` is only needed in case parameterLapses are present. Consider making optional

- [ ] How do tools not considering parameterLapses within the modelling approach cope with constraints defined as parameterLapses? Should we somehow indicate the 'nominal value' of the constraint?

- [x] Segments without `<environment> OR <endCondition> OR <mass> OR <massFraction>` can exist. Suggest setting minOccurs to 0 for this choice

- [x] `/../segments/segment/mass` -> mass should not be obligatory. Suggest setting minOccurs to 0 for this choice

- [x] `/../segments/segment/endCondition/duration` expects a time in HH:MM:SS. This is good! Adjust in documentation (now states duration in [s]

- [x] `/../segments/segment`: `<massFraction>` could be renamed to `<fuelMassFraction>` for clarity, `<mass>` could be renamed to `<fuelMass>` for clarity

- [x]  In `/../segments/segment/endCondition/`: endCondition has <positionXYZ/Z> to set the altitude, constraints has `<altitude>`. This seems inconsistent.

**Comment by CarstenChristmann** [comment]
Thank you @ErwinMoerland for sharing the issues and suggestions. Concerning the performanceRequirements node, release bfa7c91 provides the following node definition:

/cpacs/.../performanceRequirements/**flightP**erformanceReqs

This issue should be discussed in connection with #714.

**Comment by ErwinMoerland** [comment]
> 
> 
> Thank you @ErwinMoerland for sharing the issues and suggestions. Concerning the performanceRequirements node, release [bfa7c91](https://github.com/DLR-SL/CPACS/commit/bfa7c91a093bdf2eee04233cb3a9f444a7ba1138) provides the following node definition:
> 
> /cpacs/.../performanceRequirements/**flightP**erformanceReqs
> 
> This issue should be discussed in connection with #714.

@CarstenChristmann : thanks for the feedback! The node names were correct in the nodes within the CPACS file (the schema made me do it right ;)), but wrongly formulated in the Issue above. I have updated using the correct naming (i.e.: updated performanceReqs to **flight**PerformanceReqs, etc.).

**Comment by ErwinMoerland** [comment]
Now added the pointPerformanceDefinitions from @CarstenChristmann in the data deck for Diabolo as well, following issues arose:

## Concerning pointPerformanceDefinitions

- [ ] `/cpacs/.../pointPerformanceDefinition/typeOfPointPerformance` `xsd:restriction` needs following additions:
```xml
<xsd:enumeration value="level flight"/>
```
## Concerning PerformanceRequirements

concerning `/cpacs/vehicles/aircraft/model/performanceRequirements/controllabilityReqs/controllabilityReq/performanceMaps/.../specificPerformanceMap`
- [ ] does not need attribute `uID` (both the engine and aerodynamic performanceMaps)
- [ ] for a given /../specificPerformanceMaps/specificPerformanceMap, next to the obligatory performanceMapUID, either segmentUIDs or pointPerformanceUIDs MUST be given

- [ ] suggest to allow multiple pointPerformanceUIDs per controllabilityReq to avoid unnessecary repetition (i.e.: multiple pointPerformanceDefinitions for a single requirement set having the same weightAndBalance and configuration settings):
from `/cpacs/.../controllabilityReqs/controllabilityReq/pointPerformanceUID` to `/cpacs/.../controllabilityReqs/controllabilityReq/pointPerformanceUIDs/uID`

```xml
<pointPerformanceUIDs>
   <uID>Roll_Authorities_Req_01</uID>
   <uID>Roll_Authorities_Req_02</uID>
   <uID>Roll_Authorities_Req_03</uID>
</pointPerformanceUIDs>
```

**Comment by MarAlder** [comment]
> the differences in node-naming for the performanceRequirements seems confusing.
> current: `/cpacs/.../performanceRequirements/flightPerformanceReqs/flightPerformanceReq`
> suggest to rename to: `/cpacs/.../performanceRequirements/flightPerformanceRequirements/flightPerformanceRequirement`

I gree and changed it accordingly.

> `/cpacs/.../performanceMaps/.../specificPerformanceMap` does not need attribute `uID` (both the engine and aerodynamic performanceMaps)

Ok, `uID` has been removed.

> When adding child `missionDefinitions`, can the order of the obligatory children be pre-set to `missions`, `segmentBlocks`, `segments` (currently inserts: `segments`, `missions`, `segmentBlocks`)

I have adjusted the order. But since the elements are combined in one `xsd:all element, where the order is arbitrary, it is just schema cosmetics.

> `/cpacs/../missionDefinitions/missions/mission/startCondition/positionXYZ` is added without children. Force `../X`, `../Y`, `../Z` to be defined?

A bit more restricted (56e418b). Please evaluate if these values can always be provided in this context:
![grafik](https://user-images.githubusercontent.com/43143741/119786139-2c431180-bed0-11eb-9bca-0d1baa872261.png)
![grafik](https://user-images.githubusercontent.com/43143741/119786533-93f95c80-bed0-11eb-977b-86f66a3ce991.png)

> For XPATH: `/cpacs/../missionDefinitions/segmentBlocks/segmentBlock/variableSegments/variableSegment`

- `uID` removed
- `range/x|range/y|range/z` added as valid `variableConditions` (d9293fd)

> `/cpacs/.../missionDefinitions/segments/segment/segmentType` `xsd:restriction` needs following additions

Restrictions added. Interesting: 4min holdings just apply for FL140 and below wrt. PANS-OPS (see [here](https://de.wikipedia.org/wiki/Warteschleife)).

> Credit distance Y/N cannot be set yet. Suggest to add optional node to `/cpacs/.../missionDefinitions/segments/segment`

Added (4c6ed73).

> segmentType "storeRelease" needs an endCondition stating which stores are released. Proposed structure

Implemented like this:
![grafik](https://user-images.githubusercontent.com/43143741/119792826-50a1ec80-bed6-11eb-95ed-2fbf21d7b662.png)

> In `/cpacs/../segment/constraints/constraint`, the node `<continuity>` is only needed in case parameterLapses are present. Consider making optional

Done

> Segments without `<environment> OR <endCondition> OR <mass> OR <massFraction>` can exist. Suggest setting minOccurs to 0 for this choice

Done (20246a3)
 
> `/../segments/segment/mass` -> mass should not be obligatory. Suggest setting minOccurs to 0 for this choice

Should be resolved with the above change (20246a3). Or should we reorder the complete choice?
![grafik](https://user-images.githubusercontent.com/43143741/119795960-3d445080-bed9-11eb-9ba3-8f1772f0c689.png)

> `/../segments/segment/endCondition/duration` expects a time in HH:MM:SS. This is good! Adjust in documentation (now states duration in [s]

Well observed (21d7ecc).

> `/../segments/segment`: `<massFraction>` could be renamed to `<fuelMassFraction>` for clarity, `<mass>` could be renamed to `<fuelMass>` for clarity

Sounds good. Changed.

> In `/../segments/segment/endCondition/`: endCondition has <positionXYZ/Z> to set the altitude, constraints has `<altitude>`. This seems inconsistent.

Well, you can provide `endCondition/positionGeo/altitude`, right?

> `/cpacs/.../pointPerformanceDefinition/typeOfPointPerformance` `xsd:restriction` needs following additions

Yep

>  PerformanceRequirements [...] does not need attribute `uID` (both the engine and aerodynamic performanceMaps)

Fixed

> suggest to allow multiple pointPerformanceUIDs per controllabilityReq to avoid unnessecary repetition (i.e.: multiple pointPerformanceDefinitions for a single requirement set having the same weightAndBalance and configuration settings):
> from `/cpacs/.../controllabilityReqs/controllabilityReq/pointPerformanceUID` to `/cpacs/.../controllabilityReqs/controllabilityReq/pointPerformanceUIDs/uID`

Implemented in `develop`, but I want to consider @CarstenChristmann's opinion.

### Further changes

- [ ] In @ErwinMoerland's example file I noticed that the choice between segmentUID, massFraction and fuelFraction is not always required. So I set it optional.

![grafik](https://user-images.githubusercontent.com/43143741/119798932-e429ec00-bedb-11eb-8a3b-23da8a15024c.png)

- [ ] Also following @ErwinMoerland's example file I noticed that the configurationUID is not consistent between the three performanceRequirements. Thus, I adopted the version from `flightPerformanceRequirements` to `controllabilityRequirements` and `trimRequirements`:

old:
![grafik](https://user-images.githubusercontent.com/43143741/119801454-03c21400-bede-11eb-9674-6d5b9d193b42.png)

new:
![grafik](https://user-images.githubusercontent.com/43143741/119802063-834fe300-bede-11eb-915e-e0cd9180a084.png)

**Comment by MarAlder** [comment]
> for a given /../specificPerformanceMaps/specificPerformanceMap, next to the obligatory performanceMapUID, either segmentUIDs or pointPerformanceUIDs MUST be given

This can be achieved by the following XSD structure:
![grafik](https://user-images.githubusercontent.com/43143741/119810817-b0a08f00-bee6-11eb-9f7a-88693cb98a70.png)

However, **this costs us the `xsd:all` element, i.e. the sequence is fixed with `xsd:sequence`**. You also have to dig a little deeper into the meaning of the structure before you get it. If it is worth it, we can do it.

**Comment by ErwinMoerland** [comment]
> 
> 
> > for a given /../specificPerformanceMaps/specificPerformanceMap, next to the obligatory performanceMapUID, either segmentUIDs or pointPerformanceUIDs MUST be given
> 
> This can be achieved by the following XSD structure:
> ![grafik](https://user-images.githubusercontent.com/43143741/119810817-b0a08f00-bee6-11eb-9f7a-88693cb98a70.png)
> 
> However, **this costs us the `xsd:all` element, i.e. the sequence is fixed with `xsd:sequence`**. You also have to dig a little deeper into the meaning of the structure before you get it. If it is worth it, we can do it.
> 
> **Edit:** The above solution allows `segmentUIDs` and `pointPerformanceUIDs` at the same time, whereas at least one of the two must be given. It this was not the intention, an obligatory choice between `segmentUIDs` and `pointPerformanceUIDs` is of course possible as well - still need to go with `xsd:sequence`, though.

although quite complex at first sight, it seems like a working solution to me. The schema thereby completely reflects the intention of how specific performanceMaps can be given for a (set of) segmentUIDs or pointPerformanceUIDs. Some proper documentation has to be added though (note to self ;))

**Comment by MarAlder** [comment]
Thanks for all the feedback. I see a lot of checkmarks ✔️ 

@CarstenChristmann, @HHOPs, @ErwinMoerland: some final remarks? I'll otherwise try to release tomorrow.

- [XSD file](https://raw.githubusercontent.com/DLR-SL/CPACS/develop/schema/cpacs_schema.xsd)
- [Online documentations](https://www.cpacs.de/documentation/CPACS_development/html/89b6a288-0944-bd56-a1ef-8d3c8e48ad95.htm) ([chm file download](https://www.cpacs.de/documentation/CPACS_development/CPACS_Documentation.chm))

**Comment by HHOPs** [comment]
Dear @ErwinMoerland and @MarAlder,
from my point of view the mission definition has reached a good state - Thanks! Never the less I would like to leave some remarks here:

1. The switch in `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/` should contain optional values for `machNumber` and `calibratedAirSpeed`
2. The switch in `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/` should contain optional values for subsequent positional nodes (selection of local positions or fully geo-referenced defintions)...

3. The "Mission Start" definition (`/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/positionXYZ` and `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/positionGeo` should be less optional in my view, as this is a dedicated point in space. Therefore x, y and lon, lat should be obligatory here. z and alt in these nodes should be optional, as they could be derived from a terrain model via initialization or trim routine... I personally prefer to use the `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/runway` node (contains a rwy heading)...
4. Same remark as in 2. for the `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/runway/runwayStartPosition` node. Furthermore I would propose a "distance" parameter (and eventually a lateral offset) - as we are placed on the runway centerline - which would be in a relative offset to the airport reference point or rwy threshold...
5. At a later stage the node `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/positionXYZ` should state in which frame it is defined (NED, ...). This is especially crucial, as in subsequent uses of `.../positionXYZ` it is unclear, if these coordinates refer to a runway heading system or a global frame... Btw. the question of using a "flat earth" or a "geodetic reference" (WGS84, ...) has to be resolved in subsequent releases - as well as further environmental matters (EGM, WMM, ...).

6. The switch in **`/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/constraints/constraint/`** should contain optional elements as they are oposed parameters (heading angle vs. rotation angle counter)
7. The node `.../prioritySetting` should contain two optional strings: "speed" and "trajectory" - required for the flight control law to define its priorities...

8. Within **`/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/endCondition`** the following remarks:
9. The parameters `.../calibratedAirSpeed` and `.../machNumber` should be placed within a switch and optional - similar to point 1 in this listing... Optional is also a essential, as we derive a priorization - as in 7. of this list
10. `.../positionXYZ` and `.../positionGeo` should only contain optional values - as it is crucial to define "lines"/ "layers" to be crossed rather than a dedicated position (which is defined as "waypoint"). Therefore it is possible to define a segment to end in a cartesian distance or when first crossing over a geodetic position...
11. The switch in `/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/endCondition/heading` should only take optional values as they are counteracting: `.../heading` vs. `.../turnAngle` - similar point 7. in this listing
12. The "range" node (`/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/endCondition/range`) is an interesting addition to the segment definition as it allows an integration of the flown trajectory. Therefore I would like to propose it to be fully non-directional (not covered by x/y/z) - defined by a parameter "r" or similar. Then it is destinctive and a really good addition to `.../positionXYZ`.

Finally a question: The newly issued segments in `/cpacs/vehicles/aircraft/model/performanceRequirements/flightPerformanceRequirements/flightPerformanceRequirement/configurations/specificConfigurationUIDs/specificConfigurationsUID/segments/segment` directly reference the "Mission segments" - correct?

Best regards,

Richard

**Comment by MarAlder** [comment]
Well, at least my job is secured by you guys... :smirk:

Good idea numbering the (sub-)issues, so we can directly refert to it.

- [ ] 1. The switch in `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/` should contain optional values for `machNumber` and `calibratedAirSpeed`

Ok, I can make the whole choice element optional. Note: this will enable users to provide data sets without a complete set of velocity and position.

- [ ] 2. The switch in `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/` should contain optional values for subsequent positional nodes (selection of local positions or fully geo-referenced defintions)...

So, if I understand correctly: `startCondition/positionsXYZ/positionXYZ` and `startCondition/positionsGeo/positionGeo`?

- [ ] 3. The "Mission Start" definition (`/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/positionXYZ` and `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/positionGeo` should be less optional in my view, as this is a dedicated point in space. Therefore x, y and lon, lat should be obligatory here. z and alt in these nodes should be optional, as they could be derived from a terrain model via initialization or trim routine... I personally prefer to use the `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/runway` node (contains a rwy heading)...

Ok. Does this also apply to less detailed mission definitions in conceptual design, @ErwinMoerland?

- [ ] 4. Same remark as in 2. for the `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/runway/runwayStartPosition` node. Furthermore I would propose a "distance" parameter (and eventually a lateral offset) - as we are placed on the runway centerline - which would be in a relative offset to the airport reference point or rwy threshold...

I can do that as an alternative choice to xyz. So either the sequence `x`,`y`,`z` or the sequence `distance`, `lateralOffset`. As this is an additional node we can also add this in a later release if you feel unsure. 

- [ ] 5. At a later stage the node `/cpacs/vehicles/performanceCases/missionDefinitions/missions/mission/startCondition/positionXYZ` should state in which frame it is defined (NED, ...). This is especially crucial, as in subsequent uses of `.../positionXYZ` it is unclear, if these coordinates refer to a runway heading system or a global frame... Btw. the question of using a "flat earth" or a "geodetic reference" (WGS84, ...) has to be resolved in subsequent releases - as well as further environmental matters (EGM, WMM, ...).

Good point. Do we have a default for the reference system? Also something for the next release?

- [ ] 6. The switch in **`/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/constraints/constraint/`** should contain optional elements as they are oposed parameters (heading angle vs. rotation angle counter)

So making the choice element, which is the only obligatory element, optional, right?

- [ ] 7. The node `.../prioritySetting` should contain two optional strings: "speed" and "trajectory" - required for the flight control law to define its priorities...

currently implemented: `velocity` and `flightPath`. Is there a difference between `speed` and `velocity` as well as `trajectory` and `flightPath`?

- [ ] 8. Within **`/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/endCondition`** the following remarks:

- [ ] 9. The parameters `.../calibratedAirSpeed` and `.../machNumber` should be placed within a switch and optional - similar to point 1 in this listing... Optional is also a essential, as we derive a priorization - as in 7. of this list

right

- [ ] 10. `.../positionXYZ` and `.../positionGeo` should only contain optional values - as it is crucial to define "lines"/ "layers" to be crossed rather than a dedicated position (which is defined as "waypoint"). Therefore it is possible to define a segment to end in a cartesian distance or when first crossing over a geodetic position...

ok, contrary to the startCondition?

- [ ] 11. The switch in `/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/endCondition/heading` should only take optional values as they are counteracting: `.../heading` vs. `.../turnAngle` - similar point 7. in this listing

I don't get it. You have the optional choice between `heading` and `turnAngle`. Therefore, both elements at the same time is not possible.
![grafik](https://user-images.githubusercontent.com/43143741/120489319-d5e63f00-c3b7-11eb-941a-35b924f91e95.png)


- [ ] 12. The "range" node (`/cpacs/vehicles/performanceCases/missionDefinitions/segments/segment/endCondition/range`) is an interesting addition to the segment definition as it allows an integration of the flown trajectory. Therefore I would like to propose it to be fully non-directional (not covered by x/y/z) - defined by a parameter "r" or similar. Then it is destinctive and a really good addition to `.../positionXYZ`.

Good idea. So range could directly contain a double element, right?

- [ ] Finally a question: The newly issued segments in `/cpacs/vehicles/aircraft/model/performanceRequirements/flightPerformanceRequirements/flightPerformanceRequirement/configurations/specificConfigurationUIDs/specificConfigurationsUID/segments/segment` directly reference the "Mission segments" - correct?

Hmm, good observation. Was the plan not to reference the segments from the configuration itself, @ErwinMoerland and @HHOPs?
![grafik](https://user-images.githubusercontent.com/43143741/120490517-c0254980-c3b8-11eb-8237-cf7e3eb41e58.png)

**Comment by MarAlder** [comment]
Remarks to Richard's sub-issues:

1. Let's follow this strategy: for now we continue to enforce the combination of velocity+position by mandatory choice elements, taking into account that the velocity values can be specified as 0. We then put this into practice and see if cases arise where specifying the velocity actually leads to problems. In this case, we can still set the velocity choice element to optional, thus maintaining backward compatibility of the data sets.
2. I think this was a misunderstanding
3. Ok, x,y and z obligatory for position as conceptual designers are ok with providing a `0` :smirk:. For `latitude`, `longitude` and `altitude` I see different demands in the fidelity levels. Low-fi analyses usually only need the altitude information; high-fi analyses need lat and long information and derive the exact altitude from an altitude model. Therefore my decision now: all elements optional for the time being, so that all requirements are met. Make sure your tools can handle missing data at this point.  
4. Ok, I don't want to remove the RC-version (x,y,z in cartesian coordinates) so short before release. So you get both, xyz and distance+lateralOffset as a choice.
5. see remarks above
6. It turned out to be a misunderstanding. Everything kept as it is.
7. Already implemented and approved by @HHOPs 
8. nothing to do
9. done
10. done
11. The current schema already covers this. Nothing to do.
12. done
13. Nothing to do (see comment from @ErwinMoerland)

**Comment by MarAlder** [comment]
We found good solutions for the remaining issues concerning the missionDefinitions and performanceRequirements. Thanks @ErwinMoerland, @HHOPs and @CarstenChristmann for your efforts.
