### ISSUE TITLE
systemArchitecture: find better name for unmodeled components

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#822]
How about just `generic`?

![grafik](https://github.com/DLR-SL/CPACS/assets/43143741/6e27eb2f-e96c-4df8-b0ef-7dbac9b9b28a)

with:
```xml
<xsd:restriction base="stringBaseType">
    <xsd:enumeration value="ambient"/>
    <xsd:enumeration value="passengers"/>
</xsd:restriction>
```

@jbussemaker, @TimBurschyk

**Comment by jbussemaker** [comment]
I would be more in favour of something like `contextElement` or `externalElement`, because this indicates that it is an "element" relevant to modeling the system, but that it itself is not contained in the system (rather, in the system's context/environment).

"System context" and "system boundary" in general are important concepts in the world of systems engineering, as it determines what you can and cannot control (in terms of design).

**Comment by MarAlder** [comment]
Since we are in the `systemArchitecture`, I leave this completely to the system experts ;-) I'm a bit more in favor of `externalElement`, as it's more intuitive also for other domain experts (I had to read your explanation of `contextElement` twice before I got it 😏). But I would also be happy with the latter and a proper documentation.

**Comment by jbussemaker** [comment]
`externalElement` is perfectly fine in my opinion :+1:

**Comment by MarAlder** [comment]
Thanks @jbussemaker
