### ISSUE TITLE
energyCarriers: which elements need to ba aligned after renaming the fuel node?

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#827]
With CPACS v3.5 the `fuel` node will be renamed to `energyCarriers`:
![grafik](https://github.com/DLR-SL/CPACS/assets/43143741/0aa553f9-7bd5-441c-8f65-33092d195789)

CPACS users have requested that other nodes referring to `fuel` be adapted to this new terminology. I would like to get feedback on which nodes need to be renamed accordingly for CPACS v3.5.

Before we start changing some crucial CPACS nodes I want to throw some thoughts into the room: 
- ATA28 relates to `fuel` (see [here](https://de.wikipedia.org/wiki/ATA-Kapitel))
- Oxford definies `fuel` as:
    > any material that produces heat or power, usually when it is burnt

So, here some classical `fuel` elements in CPACS:
- [`massBreakdown/fuel`](https://dlr-sl.github.io/cpacs-website/documentation/CPACS_3_4_0_Docs/html/ac064609-72d6-5fd3-5b75-9eca22e7adb7.htm)/[`fuelInTank`](https://dlr-sl.github.io/cpacs-website/documentation/CPACS_3_4_0_Docs/html/bb64bb9a-d0f7-f192-8981-7689473dee46.htm)
- [`wings/.../componentSegment/wingFuelTanks`](https://dlr-sl.github.io/cpacs-website/documentation/CPACS_3_4_0_Docs/html/6a814e1f-0222-c6b8-faca-6a5efae44954.htm)
- `fuselages/fuelTanks`
- `missionDefinitions/.../fuelMass(Fraction)`
- `trajectories/.../flightPoints/fuelFlow`

So do we need to rename (some of) these nodes? Or is `fuel' still an appropriate term to refer to `chemicalEnergyCarriers'? What should be the correct terminology in aircraft design?

@DanielSilberhorn, @TimBurschyk, @marcengelmann, ...

**Comment by marcengelmann** [comment]
Hi Marko, we discussed the topic internally and in general we are ok with staying with the name fuel for all the nodes. We have some small discussion points however:
1) Regarding the split in energy carriers between fuels and electrical energy carriers, we were unsure how the two node types would differ. Depending on what the outcome of this is, we could also imagine something in the style of this:
```xml
<energyCarriers>
        <energyCarrier xsi:type="variableMassEnergyCarrierType">
            ...
        </energyCarrier>
        <energyCarrier xsi:type="constantMassEnergyCarrierType">
            ...
        </energyCarrier>
</energyCarriers>
```
At BHL we use this differentiation with xsi:type quite extensively, but there is also another way to implement this. 

2) We did this distinguishment in order have another suggestion for the flight points:

```xml
    <flightPoints>
        <energyFlows>
            <energyFlow storedEnergyCarrier="kerosene">
                <value>1;1;</value>
                <massFlow>2;2;</massFlow> <!-- OPTIONAL -->
            </energyFlow>
        </energyFlows>
    </flightPoints>
```

Because there we would be able to integrate the the energy flows and mass flows into one list. In general we like the idea to have not hardcoded kerosene flow but rather a list of flows.

3) In the fuelsInTank / fuelInTank, is it intentaional that the lowest node does not have a mass description but is of generic mass type itself? Would that not be inconsistent? 

Please just see this as a suggestion from our side to highlight what we would like to see adapted in order to dynamically cover mutliple cases. We are looking forward to discuss this of course and also would like to hear other opinions.

**Comment by MarAlder** [comment]
Thanks for the detailed feedback @marcengelmann. Point 3 is a bug in the implementation, I'll fix it, thanks! We'll get back to you on the other two points.

**Comment by MarAlder** [comment]
Sorry for the late reply. We also sat together and thought about your suggestions. Personally, I like the technical solution in point 1 of assigning different types to the element and thus specifying what kind of energyCarrier it is. However, this is more in line with our previous proposal, which led to the inconsistent naming of energyCarrier/fuel and thus to this issue. Also, I'm afraid we should not confront the CPACS community with this kind of implementation, as it adds complexity and it is hard enough to use CPACS without appropriate libraries. Therefore, I would like to assign different complex types only via explicit element names.

The second point is of course nicely consistent with the first. However, attributes should rather be used for metadata (e.g. uIDs) in CPACS. Our suggestion is to explicitly link fuels via the configurationDefinitions to specify which energy carriers are used for the aircraft model.

We propose to leave the electrical energy  carriers out of v3.5 for now and work together with you on this. Accordingly, we would keep the name `fuels` for stuff like kerosene or SAF in the future, so that we remain consistent in naming throughout CPACS.

I hope this is acceptable from BHL's point of view. We will get back to you in the new year regarding electrical energy sources.

**Comment by marcengelmann** [comment]
Hi Marko, it is ok for us to go with the way you propose for now. Of course we would appreciate to be part of any future discussions regarding this topic.

**Comment by MarAlder** [comment]
fine :)
